### PR TITLE
Mapping Overlap SNPs to Genes

### PR DESCRIPTION
**Pull request by teacheRforV**
R script for mapping overlap SNPs to genes.

### CODE REVIEW

**Comment by Selaginella99** [comment]
@teacheRforV I know I should not leave massage here. But...where can I find the the "watch" repositories unless they push updated information by notifications? Is there any "shortcut" like "starred" where I could count the number of my "watch" repos and find them more easily? Thanks!

**Comment by teacheRforV** [comment]
@Selaginella99 :smiley: 
Here it is: https://github.com/watching
https://help.github.com/articles/listing-watched-repositories/

**Comment by Selaginella99** [comment]
@teacheRforV :+1: :tulip: :tropical_drink:

**Comment by teacheRforV** [comment]
@Selaginella99 :blush: :watermelon: :bouquet:

**Pull request merged**
